SEED_JOBS = [
    {
        "title": "Mason",
        "company": "Sharma Construction",
        "industry": "construction",
        "city": "Bengaluru",
        "distance_km": 2.0,
        "salary_min": 18000,
        "salary_max": 22000,
        "experience": "2-5 Yrs",
        "job_type": "Full Time",
        "description": "We are looking for skilled masons for residential and commercial projects.",
        "requirements": ["Masonry work experience", "Can read basic instructions", "Hard working and punctual"],
        "rating": 4.2,
        "image_url": "https://images.pexels.com/photos/4483865/pexels-photo-4483865.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    },
    {
        "title": "Helper",
        "company": "BuildWell Infra",
        "industry": "construction",
        "city": "Bengaluru",
        "distance_km": 3.0,
        "salary_min": 14000,
        "salary_max": 16000,
        "experience": "Fresher",
        "job_type": "Daily Wage",
        "description": "Hardworking helpers needed for ongoing construction site.",
        "requirements": ["Physically fit", "Willing to work outdoors", "Team player"],
        "rating": 4.0,
        "image_url": "https://images.pexels.com/photos/4483865/pexels-photo-4483865.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    },
    {
        "title": "Electrician",
        "company": "PowerTech Services",
        "industry": "electrician",
        "city": "Bengaluru",
        "distance_km": 5.0,
        "salary_min": 20000,
        "salary_max": 25000,
        "experience": "1-2 Years",
        "job_type": "Full Time",
        "description": "Certified electricians needed for residential and commercial wiring projects.",
        "requirements": ["ITI Electrician certificate", "Min 1 year experience", "Own tools preferred"],
        "rating": 4.5,
        "image_url": "https://images.pexels.com/photos/34054464/pexels-photo-34054464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    },
    {
        "title": "Steel Fixer",
        "company": "Mega Infra Projects",
        "industry": "construction",
        "city": "Bengaluru",
        "distance_km": 4.0,
        "salary_min": 22000,
        "salary_max": 26000,
        "experience": "3-5 Years",
        "job_type": "Full Time",
        "description": "Experienced steel fixers required for high-rise construction.",
        "requirements": ["3+ years steel fixing experience", "Safety certified", "Ready to relocate"],
        "rating": 4.3,
        "image_url": "https://images.pexels.com/photos/4483865/pexels-photo-4483865.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    },
    {
        "title": "Painter",
        "company": "ColorPlus Services",
        "industry": "construction",
        "city": "Bengaluru",
        "distance_km": 6.0,
        "salary_min": 16000,
        "salary_max": 20000,
        "experience": "1-2 Years",
        "job_type": "Part Time",
        "description": "Professional painters for interior and exterior projects.",
        "requirements": ["Painting experience", "Good finish quality", "Own brush kit"],
        "rating": 4.1,
        "image_url": None,
    },
    {
        "title": "Delivery Executive",
        "company": "Swift Logistics",
        "industry": "delivery",
        "city": "Bengaluru",
        "distance_km": 3.5,
        "salary_min": 18000,
        "salary_max": 24000,
        "experience": "Fresher",
        "job_type": "Full Time",
        "description": "Two-wheeler delivery executives needed across city.",
        "requirements": ["Own two-wheeler", "Valid driving license", "Smartphone"],
        "rating": 4.0,
        "image_url": None,
    },
    {
        "title": "Security Guard",
        "company": "Shield Security",
        "industry": "security",
        "city": "Mysuru",
        "distance_km": 1.5,
        "salary_min": 15000,
        "salary_max": 18000,
        "experience": "Fresher",
        "job_type": "Full Time",
        "description": "Night and day shift security guards required for residential complex.",
        "requirements": ["Physical fitness", "Punctuality", "Hindi/Kannada speaking"],
        "rating": 4.2,
        "image_url": None,
    },
    {
        "title": "Plumber",
        "company": "AquaFix Services",
        "industry": "construction",
        "city": "Chennai",
        "distance_km": 4.0,
        "salary_min": 17000,
        "salary_max": 22000,
        "experience": "1-2 Years",
        "job_type": "Full Time",
        "description": "Plumbers needed for new construction sites and repairs.",
        "requirements": ["Plumbing experience", "Own tools preferred", "Local language fluency"],
        "rating": 4.0,
        "image_url": None,
    },
    {
        "title": "Factory Worker",
        "company": "Reliance Manufacturing",
        "industry": "factory",
        "city": "Pune",
        "distance_km": 8.0,
        "salary_min": 16000,
        "salary_max": 20000,
        "experience": "Fresher",
        "job_type": "Full Time",
        "description": "Assembly line operators required for manufacturing plant.",
        "requirements": ["10th pass minimum", "Willing to do shifts", "Team player"],
        "rating": 4.1,
        "image_url": None,
    },
    {
        "title": "AC Technician",
        "company": "CoolBreeze India",
        "industry": "electrician",
        "city": "Hyderabad",
        "distance_km": 6.0,
        "salary_min": 22000,
        "salary_max": 28000,
        "experience": "2-5 Yrs",
        "job_type": "Full Time",
        "description": "AC installation and repair technicians needed.",
        "requirements": ["Refrigeration course", "2+ years experience", "Two-wheeler"],
        "rating": 4.4,
        "image_url": None,
    },
    # Test job marker - explicit
    {
        "title": "Test Job - Carpenter",
        "company": "Demo Workshop",
        "industry": "construction",
        "city": "Bengaluru",
        "distance_km": 1.0,
        "salary_min": 15000,
        "salary_max": 19000,
        "experience": "1-2 Years",
        "job_type": "Daily Wage",
        "description": "This is a test job created for QA / demo purposes. Apply to validate end-to-end flow.",
        "requirements": ["Test requirement 1", "Test requirement 2"],
        "rating": 4.0,
        "image_url": None,
    },
]
